spring.datasource.url=jdbc:postgresql://localhost:5432/blog
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.main.banner-mode=off

spring.liquibase.change-log=classpath:db/db.changeLog-master.xml
spring.liquibase.enabled=true